name: Deploy Build to External gh-pages

on:
    push:
        branches:
            - main # Change this if your source branch is different

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Install dependencies and run tests
              env:
                  VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
              run: |
                  npm install
                  npm run test
                  npm run coverage
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Install and build
              env:
                  VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
              run: |
                  npm install
                  npm run build

            - name: Deploy build folder to external gh-pages
              env:
                  TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
              run: |
                  cd dist
                  git init
                  git config --global user.name "komad1na"
                  git config --global user.email "nemixalone@gmail.com"
                  git checkout -b gh-pages
                  git add .
                  git commit -m "Deploy build to gh-pages [skip ci]"
                  git push --force "https://komad1na:${TARGET_REPO_PAT}@github.com/komad1na/weather.git" gh-pages:gh-pages
