name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Push to external repo
        env:
          PERSONAL_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git config --global user.name "komad1na"
          git config --global user.email "nemixalone@gmail.com"
          git remote add external https://komad1na:${PERSONAL_TOKEN}@github.com/komad1na/weather.git
          git push external main
